title: Teorija programskih jezikov
author: Matija Pretnar
repository:
  url: 'https://github.com/matijapretnar/teorija-programskih-jezikov'
  book_path: zapiski
  branch: zapiski
launch_buttons:
  binderhub_url: 'https://mybinder.org'
